apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchbase-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase-service
  template:
    metadata:
      labels:
        app: couchbase-service
    spec:
      containers:
      - name: couchbase-service
        image: chandanghosh/couchbase-configured
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
          - containerPort: 8091
          - containerPort: 8092
          - containerPort: 8093
          - containerPort: 11210
---

apiVersion: v1
kind: Service
metadata:
  name: couchbase-service
spec:
  selector:
    app: couchbase-service #couchbase-rc-pod
  ports:
    - name: admin
      port: 8091
    - name: views
      port: 8092
    - name: query
      port: 8093
    - name: memcached
      port: 11210

---
# apiVersion: v1
# kind: ReplicationController
# metadata:
#   name: couchbase-service
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: couchbase-service
#     spec:
#       containers:
#       - name: couchbase
#         image: chandanghosh/couchbase-configured
#         ports:
#         - containerPort: 8091
#         - containerPort: 8092
#         - containerPort: 8093
#         - containerPort: 11210
