apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
spec:
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
      - name: todo-service
        image: chandanghosh/todobackend-couchbase:net5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: http
        env:
          - name: DB_SERVER
            value: couchbase-service.default.svc.cluster.local

---

apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todo-service
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer

