version: '3.4'

services:
  todoappbackend:
    image: chandanghosh/todobackend-couchbase:net5
    environment: 
      DB_SERVER: couchbase
    ports:
      - 80:80
    depends_on:
      - couchbase
    restart: on-failure #unless-stopped

  couchbase:
    image: chandanghosh/couchbase-configured:latest
    environment: 
      USERNAME: Administrator
      PASSWORD: password
      BUCKET: todo
    ports:
      - 8091-8094:8091-8094
      - 11210:11210